[package]
name = "l29_wget"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
dashmap = "6.1.0"
futures = "0.3.30"
reqwest = { version = "0.12" }
select = "0.6.0"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["rt"] }
url = "2.5.2"
