[package]
name = "l28_shell"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
shlex = "1.3.0"
nix = { version = "0.29.0", features = ["signal"] }
thiserror = "1.0.64"
